name = "ogi-route-default"
compatibility_date = "2023-12-01"
main = "src/index.ts"
account_id = "b3f9fdfd827152316d080a5ddee59915"

[env.beta]
name = "ogi-route-beta"
routes = [
  "*.koda.art/",
  "*.koda.art/sandbox.html*",
  "*.koda.art/blog/*",
  "*.koda.art/ahp/gallery/*",
  "*.koda.art/ahp/detail/*",
  "*.koda.art/ahp/collection/*",
  "*.koda.art/ahp/drops/*",
  "*.koda.art/ahp/u/*",
  "*.koda.art/ahk/gallery/*",
  "*.koda.art/ahk/detail/*",
  "*.koda.art/ahk/collection/*",
  "*.koda.art/ahk/drops/*",
  "*.koda.art/ahk/u/*",
  "*.koda.art/base/gallery/*",
  "*.koda.art/base/detail/*",
  "*.koda.art/base/collection/*",
  "*.koda.art/base/drops/*",
  "*.koda.art/base/u/*",
]

[env.production]
name = "ogi-route"
routes = [
  "koda.art/",
  "koda.art/sandbox.html*",
  "koda.art/blog/*",
  "koda.art/ahp/gallery/*",
  "koda.art/ahp/detail/*",
  "koda.art/ahp/collection/*",
  "koda.art/ahp/drops/*",
  "koda.art/ahp/u/*",
  "koda.art/ahk/gallery/*",
  "koda.art/ahk/detail/*",
  "koda.art/ahk/collection/*",
  "koda.art/ahk/drops/*",
  "koda.art/ahk/u/*",
  "koda.art/base/gallery/*",
  "koda.art/base/detail/*",
  "koda.art/base/collection/*",
  "koda.art/base/drops/*",
  "koda.art/base/u/*",
]
