name = "scheduled"
account_id = "b3f9fdfd827152316d080a5ddee59915"
main = "src/index.ts"
compatibility_date = "2023-05-31"

services = [
  { binding = "replicate", service = "replicate", environment="production" }
]

[vars]
WEBHOOK = 'https://waifu-me.kodadot.workers.dev/hookd'

[triggers]
crons = [ "*/5 * * * *" ]
